name: Custom Action
on: push
jobs:
  testing-aciton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            assignees: 'leodolan'
      - run:
          echo ${{ steps.issue.outputs.issue }}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO

