name: 'Open Github Issue'
author: Me
description: 'Opens a github issue'
inputs:
  token: 
    description: 'Github Token'
    required: true
  title:
    description: "Issue title"
    required: true
  body:
    description: 'Issue Body'
    required: true
  assignees:
    description: 'Issue Assignees'
    required: true
outputs:
  issue: # id of output
    description: 'The issue object as a json string'
runs:
  using: 'node12'
  main: 'dist/index.js'

